### ISSUE TITLE
Provide Preprocessing code

### ISSUE THREAD

**Issue by aadimator** [ziyujia/SST-EmotionNet#1]
First of all, thanks for sharing your implementation for SST-EmotionNet. Really appreciate it.

I just wanted to ask if there's a possibility that you could share SEED Dataset preprocessing code as well. It would be really helpful. Thanks.

**Comment by ziyujia** [comment]
The SEED data set has provided original data and preprocessed data (DE features, etc.). You can directly use the preprocessed data.

**Comment by aadimator** [comment]
Yes, I've seen that but your code assumes the data to be in a specific format (folder and file structure) and the way you extract spectral and temporal features and transform them to 2D Maps is also unique to you. So I was wondering if it's possible you could share that code as well (no matter how messy), so we could easily create 2D spatial-spectral and spatial-temporal representations. That would be huge help in trying to reproduce the results of the paper. Thanks a bunch.

**Comment by aadimator** [comment]
I've tried rewriting the preprocessing code taking guidance from your paper as well as code. I've managed to make the program run, but the results aren't very good. Most probably I'm doing something wrong during preprocessing. Here's what I get.

```
Subject 1:
  Session 1:0.6666666865348816
  Session 2:0.5
  Session 3:0.3333333432674408
Subject 2:
  Session 1:0.5
  Session 2:0.5
  Session 3:0.0
Subject 3:
  Session 1:0.6666666865348816
  Session 2:0.5
  Session 3:0.3333333432674408
Subject 4:
  Session 1:0.3333333432674408
  Session 2:0.0
  Session 3:0.3333333432674408
Subject 5:
  Session 1:0.6666666865348816
  Session 2:0.5
  Session 3:0.3333333432674408
Subject 6:
  Session 1:0.5
  Session 2:0.6666666865348816
  Session 3:0.8333333134651184
Subject 7:
  Session 1:0.5
  Session 2:0.3333333432674408
  Session 3:0.5
Subject 8:
  Session 1:0.5
  Session 2:0.3333333432674408
  Session 3:0.5
Subject 9:
  Session 1:0.3333333432674408
  Session 2:0.6666666865348816
  Session 3:0.6666666865348816
Subject 10:
  Session 1:0.5
  Session 2:0.5
  Session 3:0.5
Subject 11:
  Session 1:0.1666666716337204
  Session 2:0.1666666716337204
  Session 3:0.1666666716337204
Subject 12:
  Session 1:0.5
  Session 2:0.6666666865348816
  Session 3:0.0
Subject 13:
  Session 1:0.3333333432674408
  Session 2:0.1666666716337204
  Session 3:0.5
Subject 14:
  Session 1:0.5
  Session 2:0.3333333432674408
  Session 3:0.3333333432674408
Subject 15:
  Session 1:0.3333333432674408
  Session 2:0.1666666716337204
  Session 3:0.5
```

Could you take a look at the code I've written and tell me where I've made some mistake(s)?

**Comment by aadimator** [comment]
You can take a look at the code here, when and if you have time. https://github.com/aadimator/SST-EmotionNet

Thanks

**Comment by aadimator** [comment]
Can you guide me as to how you split the data into training and testing sets? In your paper, the only information is that you do 6:4 split but can you elaborate whether you pick some specific trials for training or just pick them randomly?

**Comment by ziyujia** [comment]
> Can you guide me as to how you split the data into training and testing sets? In your paper, the only information is that you do 6:4 split but can you elaborate whether you pick some specific trials for training or just pick them randomly?

The samples in each section are randomly picked.
