### ISSUE TITLE
空-时 特征

### ISSUE THREAD

**Issue by zxl260** [ziyujia/SST-EmotionNet#2]
老师您好，我是陕西师范大学的一名教育技术学研究生，现在正在进行学生脑电情绪分类这方面的学习与研究。最近看到了您的这篇关于情感脑电分类的论文(SST-EmotionNet: Spatial-Spectral-Temporal based Attention 3D Dense Network for EEG Emotion Recognition)，让我很受启发。
        但是其中让我有点疑惑的是您的时间特征是如何提取的。因为如果是200Hz的采样率，每秒就有200个数据。我看到您的SEED.ini文件中temInput_length = 25，这是不是意味着您从原始数据中每200个数据中提取25个数据来生成25个矩阵？
        希望老师有空的时候能解答一下我的疑惑，非常感谢！

**Comment by ziyujia** [comment]
您好，时域EEG信号样本在1000Hz采样率下长为200ms。在预处理时，200个数据点被下采样到25个数据点，即下采样到125Hz。

**Comment by zanzan220** [comment]
您好，能详细说一下频域的处理吗，最后采集了几个数据点呢？
