### ISSUE TITLE
How to prepropose seed data to 3D with inputwidth=32?

### ISSUE THREAD

**Issue by YeZiyi1998** [ziyujia/SST-EmotionNet#5]
In your paper "SST-EmotionNet: Spatial-Spectral-Temporal based Attention 3D Dense Network for EEG Emotion Recognition", 2D Map is 9*9, but the config of seed data in SEED.ini is inputwidth=32. I can't understand how to prepropose seed data to 3D with inputwidth=32. Could you please help me?

**Comment by 384068026** [comment]
> 在您的论文“SST-EmotionNet: Spatial-Spectral-Temporal based Attention 3D Dense Network for EEG Emotion Recognition”中，2D Map 为 9*9，但 SEED.ini 中种子数据的配置为 inputwidth=32。我不明白如何使用 inputwidth=32 将种子数据预先提议为 3D。请你帮助我好吗？

您好，能留一下您的联系方式吗？想向您请教一些问题。十分感谢！
